# Generated by Django 5.0.6 on 2024-06-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
                ('state', models.CharField(max_length=200, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Imagem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.location')),
            ],
        ),
    ]
