# Generated by Django 5.0.6 on 2024-06-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_work_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.location', verbose_name='Local'),
        ),
    ]
